spring:
  datasource:
    url: jdbc:postgresql://192.168.20.144:5432/testdeploy
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 9090
